"""
Regression tests for schema.prisma <-> generated Prisma client drift.

conftest.py stubs the `prisma` module globally with MagicMock for the other
test files, since DB calls are mocked per-test anyway. But MagicMock silently
allows access to any attribute, so it can't catch a stale generated client —
e.g. the `SearchResult` model was added to schema.prisma but `prisma generate`
was never re-run, leaving `db.searchresult` missing from the real client and
crashing `db_client.save_search_results` / `get_search_results` at runtime.

These tests bypass the conftest stub and inspect the actual installed
`prisma` package, so they fail loudly if the client goes stale again.
"""

import sys
import importlib

import pytest


def _import_real_prisma():
    """Temporarily remove the conftest MagicMock stub and import the real,
    installed `prisma` package (generated by `prisma generate`)."""
    saved = {
        name: sys.modules.pop(name)
        for name in list(sys.modules)
        if name == "prisma" or name.startswith("prisma.")
    }
    try:
        return importlib.import_module("prisma")
    finally:
        for name in list(sys.modules):
            if name == "prisma" or name.startswith("prisma."):
                del sys.modules[name]
        sys.modules.update(saved)


@pytest.fixture(scope="module")
def real_prisma():
    return _import_real_prisma()


class TestGeneratedClientMatchesSchema:
    def test_client_exposes_search_result_action(self, real_prisma):
        """schema.prisma defines `model SearchResult` — the generated client
        must expose it as `searchresult`, or save_search_results/
        get_search_results in db_client.py raise AttributeError."""
        client = real_prisma.Prisma()
        assert hasattr(client, "searchresult"), (
            "Prisma client is missing the 'searchresult' action. "
            "Run `prisma generate` after schema.prisma changes."
        )

    def test_client_exposes_product_and_pricehistory_actions(self, real_prisma):
        client = real_prisma.Prisma()
        assert hasattr(client, "product")
        assert hasattr(client, "pricehistory")

    def test_search_result_model_is_generated(self, real_prisma):
        assert hasattr(real_prisma.models, "SearchResult"), (
            "Prisma models module is missing 'SearchResult'. "
            "Run `prisma generate` after schema.prisma changes."
        )
