name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql://ci:ci@localhost:5432/ci_dummy"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - run: pip install -r requirements.txt -r requirements-dev.txt

      - run: prisma generate

      - run: python -m pytest execution/tests -v
